// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMovementSdkApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMovementSdkApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMovementSdkApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMovementSdkApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMovementSdkApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMovementSdkApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The type of location detected for a visit.
enum FSQLocationType: Int {
  case unknown = 0
  case home = 1
  case work = 2
  case venue = 3
}

/// The confidence level of a visit detection.
enum FSQConfidenceLevel: Int {
  case none = 0
  case low = 1
  case medium = 2
  case high = 3
}

/// The type of geofence event.
enum FSQGeofenceEventType: Int {
  case entrance = 0
  case dwell = 1
  case exit = 2
  case presence = 3
}

/// A geographic coordinate.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQLocation: Hashable {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQLocation? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return FSQLocation(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: FSQLocation, rhs: FSQLocation) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// Location information for a venue.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQLocationInformation: Hashable {
  var address: String? = nil
  var crossStreet: String? = nil
  var city: String? = nil
  var state: String? = nil
  var postalCode: String? = nil
  var country: String? = nil
  var location: FSQLocation? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQLocationInformation? {
    let address: String? = nilOrValue(pigeonVar_list[0])
    let crossStreet: String? = nilOrValue(pigeonVar_list[1])
    let city: String? = nilOrValue(pigeonVar_list[2])
    let state: String? = nilOrValue(pigeonVar_list[3])
    let postalCode: String? = nilOrValue(pigeonVar_list[4])
    let country: String? = nilOrValue(pigeonVar_list[5])
    let location: FSQLocation? = nilOrValue(pigeonVar_list[6])

    return FSQLocationInformation(
      address: address,
      crossStreet: crossStreet,
      city: city,
      state: state,
      postalCode: postalCode,
      country: country,
      location: location
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      crossStreet,
      city,
      state,
      postalCode,
      country,
      location,
    ]
  }
  static func == (lhs: FSQLocationInformation, rhs: FSQLocationInformation) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// Icon image information for a category.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQCategoryIcon: Hashable {
  var prefix: String
  var suffix: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQCategoryIcon? {
    let prefix = pigeonVar_list[0] as! String
    let suffix = pigeonVar_list[1] as! String

    return FSQCategoryIcon(
      prefix: prefix,
      suffix: suffix
    )
  }
  func toList() -> [Any?] {
    return [
      prefix,
      suffix,
    ]
  }
  static func == (lhs: FSQCategoryIcon, rhs: FSQCategoryIcon) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// A Foursquare category for a venue.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQCategory: Hashable {
  var id: String
  var name: String
  var pluralName: String? = nil
  var shortName: String? = nil
  var icon: FSQCategoryIcon? = nil
  var isPrimary: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQCategory? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let pluralName: String? = nilOrValue(pigeonVar_list[2])
    let shortName: String? = nilOrValue(pigeonVar_list[3])
    let icon: FSQCategoryIcon? = nilOrValue(pigeonVar_list[4])
    let isPrimary = pigeonVar_list[5] as! Bool

    return FSQCategory(
      id: id,
      name: name,
      pluralName: pluralName,
      shortName: shortName,
      icon: icon,
      isPrimary: isPrimary
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      pluralName,
      shortName,
      icon,
      isPrimary,
    ]
  }
  static func == (lhs: FSQCategory, rhs: FSQCategory) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// A Foursquare chain (e.g., Starbucks).
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQChain: Hashable {
  var id: String
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQChain? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String

    return FSQChain(
      id: id,
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
    ]
  }
  static func == (lhs: FSQChain, rhs: FSQChain) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// Parent venue in a hierarchy.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQVenueParent: Hashable {
  var id: String
  var name: String
  var categories: [FSQCategory]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQVenueParent? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let categories = pigeonVar_list[2] as! [FSQCategory]

    return FSQVenueParent(
      id: id,
      name: name,
      categories: categories
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      categories,
    ]
  }
  static func == (lhs: FSQVenueParent, rhs: FSQVenueParent) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// A venue in the Foursquare Places database.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQVenue: Hashable {
  var id: String
  var name: String
  var locationInformation: FSQLocationInformation? = nil
  var partnerVenueId: String? = nil
  var probability: Double? = nil
  var chains: [FSQChain]
  var categories: [FSQCategory]
  var hierarchy: [FSQVenueParent]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQVenue? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let locationInformation: FSQLocationInformation? = nilOrValue(pigeonVar_list[2])
    let partnerVenueId: String? = nilOrValue(pigeonVar_list[3])
    let probability: Double? = nilOrValue(pigeonVar_list[4])
    let chains = pigeonVar_list[5] as! [FSQChain]
    let categories = pigeonVar_list[6] as! [FSQCategory]
    let hierarchy = pigeonVar_list[7] as! [FSQVenueParent]

    return FSQVenue(
      id: id,
      name: name,
      locationInformation: locationInformation,
      partnerVenueId: partnerVenueId,
      probability: probability,
      chains: chains,
      categories: categories,
      hierarchy: hierarchy
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      locationInformation,
      partnerVenueId,
      probability,
      chains,
      categories,
      hierarchy,
    ]
  }
  static func == (lhs: FSQVenue, rhs: FSQVenue) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// Everything the Movement SDK knows about a user's location.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQVisit: Hashable {
  /// Unique identifier for this visit, if available.
  var id: String? = nil
  var location: FSQLocation? = nil
  var locationType: FSQLocationType
  var confidence: FSQConfidenceLevel
  var arrivalTime: Int64? = nil
  var venue: FSQVenue? = nil
  var otherPossibleVenues: [FSQVenue]
  /// Whether the user has departed from this visit.
  var hasDeparted: Bool
  /// Departure time as milliseconds since epoch, if departed.
  var departureTime: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQVisit? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let location: FSQLocation? = nilOrValue(pigeonVar_list[1])
    let locationType = pigeonVar_list[2] as! FSQLocationType
    let confidence = pigeonVar_list[3] as! FSQConfidenceLevel
    let arrivalTime: Int64? = nilOrValue(pigeonVar_list[4])
    let venue: FSQVenue? = nilOrValue(pigeonVar_list[5])
    let otherPossibleVenues = pigeonVar_list[6] as! [FSQVenue]
    let hasDeparted = pigeonVar_list[7] as! Bool
    let departureTime: Int64? = nilOrValue(pigeonVar_list[8])

    return FSQVisit(
      id: id,
      location: location,
      locationType: locationType,
      confidence: confidence,
      arrivalTime: arrivalTime,
      venue: venue,
      otherPossibleVenues: otherPossibleVenues,
      hasDeparted: hasDeparted,
      departureTime: departureTime
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      location,
      locationType,
      confidence,
      arrivalTime,
      venue,
      otherPossibleVenues,
      hasDeparted,
      departureTime,
    ]
  }
  static func == (lhs: FSQVisit, rhs: FSQVisit) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// An interaction with one or more registered geofence radii.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQGeofenceEvent: Hashable {
  var geofenceId: String
  var name: String
  var eventType: FSQGeofenceEventType
  var venueId: String? = nil
  var venue: FSQVenue? = nil
  var partnerVenueId: String? = nil
  var location: FSQLocation
  var timestamp: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQGeofenceEvent? {
    let geofenceId = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let eventType = pigeonVar_list[2] as! FSQGeofenceEventType
    let venueId: String? = nilOrValue(pigeonVar_list[3])
    let venue: FSQVenue? = nilOrValue(pigeonVar_list[4])
    let partnerVenueId: String? = nilOrValue(pigeonVar_list[5])
    let location = pigeonVar_list[6] as! FSQLocation
    let timestamp = pigeonVar_list[7] as! Int64

    return FSQGeofenceEvent(
      geofenceId: geofenceId,
      name: name,
      eventType: eventType,
      venueId: venueId,
      venue: venue,
      partnerVenueId: partnerVenueId,
      location: location,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      geofenceId,
      name,
      eventType,
      venueId,
      venue,
      partnerVenueId,
      location,
      timestamp,
    ]
  }
  static func == (lhs: FSQGeofenceEvent, rhs: FSQGeofenceEvent) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// The current location of the user.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQCurrentLocation: Hashable {
  var currentPlace: FSQVisit
  var matchedGeofences: [FSQGeofenceEvent]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQCurrentLocation? {
    let currentPlace = pigeonVar_list[0] as! FSQVisit
    let matchedGeofences = pigeonVar_list[1] as! [FSQGeofenceEvent]

    return FSQCurrentLocation(
      currentPlace: currentPlace,
      matchedGeofences: matchedGeofences
    )
  }
  func toList() -> [Any?] {
    return [
      currentPlace,
      matchedGeofences,
    ]
  }
  static func == (lhs: FSQCurrentLocation, rhs: FSQCurrentLocation) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

/// A single entry from the native SDK's debug log buffer.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FSQDebugLogEntry: Hashable {
  /// Milliseconds since epoch when the log was recorded.
  var timestamp: Int64
  /// Severity: "debug", "info", "warn", or "error".
  var level: String
  /// Log source category. iOS provides granular types ("network", "location",
  /// "geofence", etc.); Android always returns "general".
  var type: String
  /// Human-readable description of the event.
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FSQDebugLogEntry? {
    let timestamp = pigeonVar_list[0] as! Int64
    let level = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! String
    let message = pigeonVar_list[3] as! String

    return FSQDebugLogEntry(
      timestamp: timestamp,
      level: level,
      type: type,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      timestamp,
      level,
      type,
      message,
    ]
  }
  static func == (lhs: FSQDebugLogEntry, rhs: FSQDebugLogEntry) -> Bool {
    return deepEqualsMovementSdkApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMovementSdkApi(value: toList(), hasher: &hasher)
  }
}

private class MovementSdkApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FSQLocationType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FSQConfidenceLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FSQGeofenceEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return FSQLocation.fromList(self.readValue() as! [Any?])
    case 133:
      return FSQLocationInformation.fromList(self.readValue() as! [Any?])
    case 134:
      return FSQCategoryIcon.fromList(self.readValue() as! [Any?])
    case 135:
      return FSQCategory.fromList(self.readValue() as! [Any?])
    case 136:
      return FSQChain.fromList(self.readValue() as! [Any?])
    case 137:
      return FSQVenueParent.fromList(self.readValue() as! [Any?])
    case 138:
      return FSQVenue.fromList(self.readValue() as! [Any?])
    case 139:
      return FSQVisit.fromList(self.readValue() as! [Any?])
    case 140:
      return FSQGeofenceEvent.fromList(self.readValue() as! [Any?])
    case 141:
      return FSQCurrentLocation.fromList(self.readValue() as! [Any?])
    case 142:
      return FSQDebugLogEntry.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MovementSdkApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FSQLocationType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? FSQConfidenceLevel {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? FSQGeofenceEventType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? FSQLocation {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? FSQLocationInformation {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? FSQCategoryIcon {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? FSQCategory {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? FSQChain {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? FSQVenueParent {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? FSQVenue {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? FSQVisit {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? FSQGeofenceEvent {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? FSQCurrentLocation {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? FSQDebugLogEntry {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MovementSdkApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MovementSdkApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MovementSdkApiPigeonCodecWriter(data: data)
  }
}

class MovementSdkApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MovementSdkApiPigeonCodec(readerWriter: MovementSdkApiPigeonCodecReaderWriter())
}


/// Host API for Movement SDK operations.
/// Implemented by the native platform (iOS/Android).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MovementSdkHostApi {
  /// Returns a unique identifier generated the first time the SDK runs on a device.
  func getInstallId(completion: @escaping (Result<String, Error>) -> Void)
  /// Starts the SDK and begins receiving location updates.
  func start() throws
  /// Stops receiving location updates until [start] is called again.
  func stop() throws
  /// Gets the current location of the user, including venue and geofences.
  func getCurrentLocation(completion: @escaping (Result<FSQCurrentLocation, Error>) -> Void)
  /// Returns whether the Movement SDK is currently enabled.
  func isEnabled(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Generates a test visit at the given location for debugging.
  func fireTestVisit(latitude: Double, longitude: Double) throws
  /// Shows the debug screen for viewing Movement SDK logs.
  func showDebugScreen() throws
  /// Gets the current user info for server-to-server notifications.
  func getUserInfo(completion: @escaping (Result<[String: String], Error>) -> Void)
  /// Sets user info for server-to-server visit notifications.
  func setUserInfo(userInfo: [String: String], persisted: Bool) throws
  /// Sets the user ID for server-to-server visit notifications.
  ///
  /// This uses the dedicated native setter which is required for the
  /// predefined "userId" key (the generic setUserInfo silently ignores it on iOS).
  func setUserId(userId: String, persisted: Bool) throws
  /// Clears all data including unique identifiers and cached data.
  ///
  /// Should be called when a user logs out of your app.
  func clearAllData() throws
  /// Returns the currently active visit, or null if there is no active visit.
  func getActiveVisit(completion: @escaping (Result<FSQVisit?, Error>) -> Void)
  /// Returns recent debug log entries collected by the native SDK.
  ///
  /// Requires debug logging to be enabled natively
  /// (`isDebugLogsEnabled` on iOS, `setEnableDebugLogs` on Android).
  func getDebugLogs(completion: @escaping (Result<[FSQDebugLogEntry], Error>) -> Void)
  /// Clears the native SDK's debug log buffer.
  func clearDebugLogs() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MovementSdkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MovementSdkApiPigeonCodec.shared }
  /// Sets up an instance of `MovementSdkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MovementSdkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns a unique identifier generated the first time the SDK runs on a device.
    let getInstallIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getInstallId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInstallIdChannel.setMessageHandler { _, reply in
        api.getInstallId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getInstallIdChannel.setMessageHandler(nil)
    }
    /// Starts the SDK and begins receiving location updates.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        do {
          try api.start()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Stops receiving location updates until [start] is called again.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Gets the current location of the user, including venue and geofences.
    let getCurrentLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getCurrentLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentLocationChannel.setMessageHandler { _, reply in
        api.getCurrentLocation { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCurrentLocationChannel.setMessageHandler(nil)
    }
    /// Returns whether the Movement SDK is currently enabled.
    let isEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.isEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isEnabledChannel.setMessageHandler { _, reply in
        api.isEnabled { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isEnabledChannel.setMessageHandler(nil)
    }
    /// Generates a test visit at the given location for debugging.
    let fireTestVisitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.fireTestVisit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fireTestVisitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let latitudeArg = args[0] as! Double
        let longitudeArg = args[1] as! Double
        do {
          try api.fireTestVisit(latitude: latitudeArg, longitude: longitudeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fireTestVisitChannel.setMessageHandler(nil)
    }
    /// Shows the debug screen for viewing Movement SDK logs.
    let showDebugScreenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.showDebugScreen\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showDebugScreenChannel.setMessageHandler { _, reply in
        do {
          try api.showDebugScreen()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showDebugScreenChannel.setMessageHandler(nil)
    }
    /// Gets the current user info for server-to-server notifications.
    let getUserInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getUserInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserInfoChannel.setMessageHandler { _, reply in
        api.getUserInfo { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUserInfoChannel.setMessageHandler(nil)
    }
    /// Sets user info for server-to-server visit notifications.
    let setUserInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.setUserInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userInfoArg = args[0] as! [String: String]
        let persistedArg = args[1] as! Bool
        do {
          try api.setUserInfo(userInfo: userInfoArg, persisted: persistedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserInfoChannel.setMessageHandler(nil)
    }
    /// Sets the user ID for server-to-server visit notifications.
    ///
    /// This uses the dedicated native setter which is required for the
    /// predefined "userId" key (the generic setUserInfo silently ignores it on iOS).
    let setUserIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.setUserId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userIdArg = args[0] as! String
        let persistedArg = args[1] as! Bool
        do {
          try api.setUserId(userId: userIdArg, persisted: persistedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserIdChannel.setMessageHandler(nil)
    }
    /// Clears all data including unique identifiers and cached data.
    ///
    /// Should be called when a user logs out of your app.
    let clearAllDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.clearAllData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAllDataChannel.setMessageHandler { _, reply in
        do {
          try api.clearAllData()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAllDataChannel.setMessageHandler(nil)
    }
    /// Returns the currently active visit, or null if there is no active visit.
    let getActiveVisitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getActiveVisit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getActiveVisitChannel.setMessageHandler { _, reply in
        api.getActiveVisit { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getActiveVisitChannel.setMessageHandler(nil)
    }
    /// Returns recent debug log entries collected by the native SDK.
    ///
    /// Requires debug logging to be enabled natively
    /// (`isDebugLogsEnabled` on iOS, `setEnableDebugLogs` on Android).
    let getDebugLogsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getDebugLogs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDebugLogsChannel.setMessageHandler { _, reply in
        api.getDebugLogs { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDebugLogsChannel.setMessageHandler(nil)
    }
    /// Clears the native SDK's debug log buffer.
    let clearDebugLogsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.clearDebugLogs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearDebugLogsChannel.setMessageHandler { _, reply in
        do {
          try api.clearDebugLogs()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearDebugLogsChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API for receiving real-time events from the native SDK.
/// Implemented on the Dart side, called by native code.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MovementSdkFlutterApiProtocol {
  /// Called when the user arrives at or departs from a place.
  func onVisit(visit visitArg: FSQVisit, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called for visits that occurred when there was no network connectivity.
  func onBackfillVisit(visit visitArg: FSQVisit, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when geofence events are triggered.
  func onGeofenceEvents(events eventsArg: [FSQGeofenceEvent], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MovementSdkFlutterApi: MovementSdkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MovementSdkApiPigeonCodec {
    return MovementSdkApiPigeonCodec.shared
  }
  /// Called when the user arrives at or departs from a place.
  func onVisit(visit visitArg: FSQVisit, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkFlutterApi.onVisit\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([visitArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called for visits that occurred when there was no network connectivity.
  func onBackfillVisit(visit visitArg: FSQVisit, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkFlutterApi.onBackfillVisit\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([visitArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when geofence events are triggered.
  func onGeofenceEvents(events eventsArg: [FSQGeofenceEvent], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkFlutterApi.onGeofenceEvents\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
