// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.atmosphere.foursquare_movement_sdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MovementSdkApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** The type of location detected for a visit. */
enum class FSQLocationType(val raw: Int) {
  UNKNOWN(0),
  HOME(1),
  WORK(2),
  VENUE(3);

  companion object {
    fun ofRaw(raw: Int): FSQLocationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The confidence level of a visit detection. */
enum class FSQConfidenceLevel(val raw: Int) {
  NONE(0),
  LOW(1),
  MEDIUM(2),
  HIGH(3);

  companion object {
    fun ofRaw(raw: Int): FSQConfidenceLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The type of geofence event. */
enum class FSQGeofenceEventType(val raw: Int) {
  ENTRANCE(0),
  DWELL(1),
  EXIT(2),
  PRESENCE(3);

  companion object {
    fun ofRaw(raw: Int): FSQGeofenceEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A geographic coordinate.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQLocation (
  val latitude: Double,
  val longitude: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQLocation {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      return FSQLocation(latitude, longitude)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQLocation) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Location information for a venue.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQLocationInformation (
  val address: String? = null,
  val crossStreet: String? = null,
  val city: String? = null,
  val state: String? = null,
  val postalCode: String? = null,
  val country: String? = null,
  val location: FSQLocation? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQLocationInformation {
      val address = pigeonVar_list[0] as String?
      val crossStreet = pigeonVar_list[1] as String?
      val city = pigeonVar_list[2] as String?
      val state = pigeonVar_list[3] as String?
      val postalCode = pigeonVar_list[4] as String?
      val country = pigeonVar_list[5] as String?
      val location = pigeonVar_list[6] as FSQLocation?
      return FSQLocationInformation(address, crossStreet, city, state, postalCode, country, location)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      crossStreet,
      city,
      state,
      postalCode,
      country,
      location,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQLocationInformation) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Icon image information for a category.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQCategoryIcon (
  val prefix: String,
  val suffix: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQCategoryIcon {
      val prefix = pigeonVar_list[0] as String
      val suffix = pigeonVar_list[1] as String
      return FSQCategoryIcon(prefix, suffix)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      prefix,
      suffix,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQCategoryIcon) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A Foursquare category for a venue.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQCategory (
  val id: String,
  val name: String,
  val pluralName: String? = null,
  val shortName: String? = null,
  val icon: FSQCategoryIcon? = null,
  val isPrimary: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQCategory {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val pluralName = pigeonVar_list[2] as String?
      val shortName = pigeonVar_list[3] as String?
      val icon = pigeonVar_list[4] as FSQCategoryIcon?
      val isPrimary = pigeonVar_list[5] as Boolean
      return FSQCategory(id, name, pluralName, shortName, icon, isPrimary)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      pluralName,
      shortName,
      icon,
      isPrimary,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQCategory) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A Foursquare chain (e.g., Starbucks).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQChain (
  val id: String,
  val name: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQChain {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      return FSQChain(id, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQChain) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Parent venue in a hierarchy.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQVenueParent (
  val id: String,
  val name: String,
  val categories: List<FSQCategory>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQVenueParent {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val categories = pigeonVar_list[2] as List<FSQCategory>
      return FSQVenueParent(id, name, categories)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      categories,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQVenueParent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * A venue in the Foursquare Places database.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQVenue (
  val id: String,
  val name: String,
  val locationInformation: FSQLocationInformation? = null,
  val partnerVenueId: String? = null,
  val probability: Double? = null,
  val chains: List<FSQChain>,
  val categories: List<FSQCategory>,
  val hierarchy: List<FSQVenueParent>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQVenue {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val locationInformation = pigeonVar_list[2] as FSQLocationInformation?
      val partnerVenueId = pigeonVar_list[3] as String?
      val probability = pigeonVar_list[4] as Double?
      val chains = pigeonVar_list[5] as List<FSQChain>
      val categories = pigeonVar_list[6] as List<FSQCategory>
      val hierarchy = pigeonVar_list[7] as List<FSQVenueParent>
      return FSQVenue(id, name, locationInformation, partnerVenueId, probability, chains, categories, hierarchy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      locationInformation,
      partnerVenueId,
      probability,
      chains,
      categories,
      hierarchy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQVenue) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Everything the Movement SDK knows about a user's location.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQVisit (
  /** Unique identifier for this visit, if available. */
  val id: String? = null,
  val location: FSQLocation? = null,
  val locationType: FSQLocationType,
  val confidence: FSQConfidenceLevel,
  val arrivalTime: Long? = null,
  val venue: FSQVenue? = null,
  val otherPossibleVenues: List<FSQVenue>,
  /** Whether the user has departed from this visit. */
  val hasDeparted: Boolean,
  /** Departure time as milliseconds since epoch, if departed. */
  val departureTime: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQVisit {
      val id = pigeonVar_list[0] as String?
      val location = pigeonVar_list[1] as FSQLocation?
      val locationType = pigeonVar_list[2] as FSQLocationType
      val confidence = pigeonVar_list[3] as FSQConfidenceLevel
      val arrivalTime = pigeonVar_list[4] as Long?
      val venue = pigeonVar_list[5] as FSQVenue?
      val otherPossibleVenues = pigeonVar_list[6] as List<FSQVenue>
      val hasDeparted = pigeonVar_list[7] as Boolean
      val departureTime = pigeonVar_list[8] as Long?
      return FSQVisit(id, location, locationType, confidence, arrivalTime, venue, otherPossibleVenues, hasDeparted, departureTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      location,
      locationType,
      confidence,
      arrivalTime,
      venue,
      otherPossibleVenues,
      hasDeparted,
      departureTime,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQVisit) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * An interaction with one or more registered geofence radii.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQGeofenceEvent (
  val geofenceId: String,
  val name: String,
  val eventType: FSQGeofenceEventType,
  val venueId: String? = null,
  val venue: FSQVenue? = null,
  val partnerVenueId: String? = null,
  val location: FSQLocation,
  val timestamp: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQGeofenceEvent {
      val geofenceId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val eventType = pigeonVar_list[2] as FSQGeofenceEventType
      val venueId = pigeonVar_list[3] as String?
      val venue = pigeonVar_list[4] as FSQVenue?
      val partnerVenueId = pigeonVar_list[5] as String?
      val location = pigeonVar_list[6] as FSQLocation
      val timestamp = pigeonVar_list[7] as Long
      return FSQGeofenceEvent(geofenceId, name, eventType, venueId, venue, partnerVenueId, location, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      geofenceId,
      name,
      eventType,
      venueId,
      venue,
      partnerVenueId,
      location,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQGeofenceEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * The current location of the user.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FSQCurrentLocation (
  val currentPlace: FSQVisit,
  val matchedGeofences: List<FSQGeofenceEvent>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FSQCurrentLocation {
      val currentPlace = pigeonVar_list[0] as FSQVisit
      val matchedGeofences = pigeonVar_list[1] as List<FSQGeofenceEvent>
      return FSQCurrentLocation(currentPlace, matchedGeofences)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      currentPlace,
      matchedGeofences,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FSQCurrentLocation) {
      return false
    }
    if (this === other) {
      return true
    }
    return MovementSdkApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MovementSdkApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FSQLocationType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FSQConfidenceLevel.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FSQGeofenceEventType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQLocation.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQLocationInformation.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQCategoryIcon.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQCategory.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQChain.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQVenueParent.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQVenue.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQVisit.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQGeofenceEvent.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FSQCurrentLocation.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FSQLocationType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is FSQConfidenceLevel -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is FSQGeofenceEventType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is FSQLocation -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is FSQLocationInformation -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is FSQCategoryIcon -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is FSQCategory -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is FSQChain -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is FSQVenueParent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is FSQVenue -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is FSQVisit -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is FSQGeofenceEvent -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is FSQCurrentLocation -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for Movement SDK operations.
 * Implemented by the native platform (iOS/Android).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MovementSdkHostApi {
  /** Returns a unique identifier generated the first time the SDK runs on a device. */
  fun getInstallId(callback: (Result<String>) -> Unit)
  /** Starts the SDK and begins receiving location updates. */
  fun start()
  /** Stops receiving location updates until [start] is called again. */
  fun stop()
  /** Gets the current location of the user, including venue and geofences. */
  fun getCurrentLocation(callback: (Result<FSQCurrentLocation>) -> Unit)
  /** Returns whether the Movement SDK is currently enabled. */
  fun isEnabled(callback: (Result<Boolean>) -> Unit)
  /** Generates a test visit at the given location for debugging. */
  fun fireTestVisit(latitude: Double, longitude: Double)
  /** Shows the debug screen for viewing Movement SDK logs. */
  fun showDebugScreen()
  /** Gets the current user info for server-to-server notifications. */
  fun getUserInfo(callback: (Result<Map<String, String>>) -> Unit)
  /** Sets user info for server-to-server visit notifications. */
  fun setUserInfo(userInfo: Map<String, String>, persisted: Boolean)
  /**
   * Sets the user ID for server-to-server visit notifications.
   *
   * This uses the dedicated native setter which is required for the
   * predefined "userId" key (the generic setUserInfo silently ignores it on iOS).
   */
  fun setUserId(userId: String, persisted: Boolean)
  /**
   * Clears all data including unique identifiers and cached data.
   *
   * Should be called when a user logs out of your app.
   */
  fun clearAllData()
  /** Returns the currently active visit, or null if there is no active visit. */
  fun getActiveVisit(callback: (Result<FSQVisit?>) -> Unit)

  companion object {
    /** The codec used by MovementSdkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MovementSdkApiPigeonCodec()
    }
    /** Sets up an instance of `MovementSdkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MovementSdkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getInstallId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstallId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MovementSdkApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MovementSdkApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.start()
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getCurrentLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCurrentLocation{ result: Result<FSQCurrentLocation> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MovementSdkApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MovementSdkApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.isEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isEnabled{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MovementSdkApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MovementSdkApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.fireTestVisit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val latitudeArg = args[0] as Double
            val longitudeArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.fireTestVisit(latitudeArg, longitudeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.showDebugScreen$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.showDebugScreen()
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getUserInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getUserInfo{ result: Result<Map<String, String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MovementSdkApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MovementSdkApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.setUserInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userInfoArg = args[0] as Map<String, String>
            val persistedArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setUserInfo(userInfoArg, persistedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.setUserId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userIdArg = args[0] as String
            val persistedArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setUserId(userIdArg, persistedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.clearAllData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAllData()
              listOf(null)
            } catch (exception: Throwable) {
              MovementSdkApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkHostApi.getActiveVisit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getActiveVisit{ result: Result<FSQVisit?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MovementSdkApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MovementSdkApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API for receiving real-time events from the native SDK.
 * Implemented on the Dart side, called by native code.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class MovementSdkFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MovementSdkFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MovementSdkApiPigeonCodec()
    }
  }
  /** Called when the user arrives at or departs from a place. */
  fun onVisit(visitArg: FSQVisit, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkFlutterApi.onVisit$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(visitArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MovementSdkApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called for visits that occurred when there was no network connectivity. */
  fun onBackfillVisit(visitArg: FSQVisit, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkFlutterApi.onBackfillVisit$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(visitArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MovementSdkApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when geofence events are triggered. */
  fun onGeofenceEvents(eventsArg: List<FSQGeofenceEvent>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.foursquare_movement_sdk.MovementSdkFlutterApi.onGeofenceEvents$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MovementSdkApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
